version: '3'

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: posthog
      POSTGRES_DB: posthog
  web:
    image: posthog/posthog:latest
    ports:
      - "8000:8000"
    environment:
      IS_DOCKER: "true"
      DATABASE_URL: "postgres://posthog@db:5432/posthog"
      SECRET_KEY: "<randomly generated secret key>"
      DEBUG: "true"
    depends_on:
      - db
