apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "posthog.fullname" . }}
  labels:
    {{- include "posthog.labels" . | nindent 4 }}
data:
{{- range $k, $v := .Values.environmentVariables }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
