apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "posthog.fullname" . }}-beat
  labels:
    {{- include "posthog.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "posthog.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        tag: {{ .Values.image.tag }}
      labels:
        {{- include "posthog.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            limits:
              cpu: 50m
              memory: 96Mi
            requests:
              cpu: 1m
              memory: 32Mi
          env:
            - name: DEBUG
              value: "False"
            - name: STATIC_URL
              value: /
            - name: SERVER_ROLE
              value: "beat"
          envFrom:
            - secretRef:
                name: {{ include "posthog.fullname" . }}
            - configMapRef:
                name: {{ include "posthog.fullname" . }}
