apiVersion: v1
kind: Secret
metadata:
  name: {{ include "posthog.fullname" . }}
  labels:
    {{- include "posthog.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ required "databaseURL is a required value." .Values.databaseURL | b64enc | quote }}
  SECRET_KEY: {{ required "secretKey is a required value." .Values.secretKey | b64enc | quote }}
