{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "posthog.serviceAccountName" . }}
  labels:
{{ include "posthog.labels" . | nindent 4 }}
{{- end -}}
