# Generated by Django 3.2.14 on 2023-01-07 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytickit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="plugins_access_level",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "none"), (3, "config"), (6, "install"), (9, "root")], default=3
            ),
        ),
    ]
