# Generated by Django 3.2.14 on 2023-09-01 14:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('analytickit', '0003_communityengagement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityengagement',
            name='active_users',
        ),
        migrations.RemoveField(
            model_name='communityengagement',
            name='ave_gas_used',
        ),
        migrations.RemoveField(
            model_name='communityengagement',
            name='ave_token_transfer_value',
        ),
        migrations.RemoveField(
            model_name='communityengagement',
            name='ave_txn_fee',
        ),
        migrations.RemoveField(
            model_name='communityengagement',
            name='average_gas_used',
        ),
        migrations.RemoveField(
            model_name='communityengagement',
            name='date',
        ),
        migrations.RemoveField(
            model_name='communityengagement',
            name='freq_txn',
        ),
        migrations.RemoveField(
            model_name='communityengagement',
            name='function_calls_count',
        ),
        migrations.RemoveField(
            model_name='communityengagement',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='communityengagement',
            name='most_active_token_addresses',
        ),
        migrations.RemoveField(
            model_name='communityengagement',
            name='referral_count',
        ),
        migrations.RemoveField(
            model_name='communityengagement',
            name='token_flow',
        ),
        migrations.RemoveField(
            model_name='communityengagement',
            name='token_transfer_value',
        ),
        migrations.RemoveField(
            model_name='communityengagement',
            name='token_transfer_value_distribution',
        ),
        migrations.RemoveField(
            model_name='communityengagement',
            name='token_transfer_volume',
        ),
        migrations.RemoveField(
            model_name='communityengagement',
            name='tot_tokens_transferred',
        ),
        migrations.RemoveField(
            model_name='communityengagement',
            name='tot_txn_from_address',
        ),
        migrations.RemoveField(
            model_name='communityengagement',
            name='tot_txn_to_address',
        ),
        migrations.RemoveField(
            model_name='communityengagement',
            name='tot_txns',
        ),
        migrations.RemoveField(
            model_name='communityengagement',
            name='total_contract_calls',
        ),
        migrations.RemoveField(
            model_name='communityengagement',
            name='transaction_value_distribution',
        ),
        migrations.AddField(
            model_name='communityengagement',
            name='creation_ts',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='communityengagement',
            name='update_ts',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 1, 14, 23, 58, 389047, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CampaignAnalytic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_ts', models.DateTimeField()),
                ('update_ts', models.DateTimeField()),
                ('active_users', models.IntegerField()),
                ('total_contract_calls', models.IntegerField()),
                ('average_gas_used', models.DecimalField(decimal_places=5, max_digits=20)),
                ('function_calls_count', models.JSONField()),
                ('tot_tokens_transferred', models.DecimalField(decimal_places=10, max_digits=30)),
                ('referral_count', models.IntegerField()),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('tot_txns', models.IntegerField()),
                ('ave_gas_used', models.DecimalField(decimal_places=5, max_digits=20)),
                ('transaction_value_distribution', models.JSONField()),
                ('ave_txn_fee', models.DecimalField(decimal_places=5, max_digits=20)),
                ('tot_txn_from_address', models.JSONField()),
                ('tot_txn_to_address', models.JSONField()),
                ('freq_txn', models.JSONField()),
                ('token_transfer_volume', models.DecimalField(decimal_places=10, max_digits=30)),
                ('token_transfer_value', models.DecimalField(decimal_places=10, max_digits=30)),
                ('most_active_token_addresses', models.JSONField()),
                ('ave_token_transfer_value', models.DecimalField(decimal_places=10, max_digits=30)),
                ('token_flow', models.JSONField()),
                ('token_transfer_value_distribution', models.JSONField()),
                ('community_engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytickit.communityengagement')),
            ],
        ),
    ]
