# Generated by Django 3.2.14 on 2023-09-06 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytickit', '0005_s3file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignanalytic',
            name='active_users',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='campaignanalytic',
            name='ave_gas_used',
            field=models.DecimalField(decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='campaignanalytic',
            name='ave_token_transfer_value',
            field=models.DecimalField(decimal_places=10, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='campaignanalytic',
            name='ave_txn_fee',
            field=models.DecimalField(decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='campaignanalytic',
            name='average_gas_used',
            field=models.DecimalField(decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='campaignanalytic',
            name='community_engagement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='analytickit.communityengagement'),
        ),
        migrations.AlterField(
            model_name='campaignanalytic',
            name='creation_ts',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='campaignanalytic',
            name='freq_txn',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='campaignanalytic',
            name='function_calls_count',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='campaignanalytic',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaignanalytic',
            name='most_active_token_addresses',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='campaignanalytic',
            name='referral_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='campaignanalytic',
            name='token_flow',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='campaignanalytic',
            name='token_transfer_value',
            field=models.DecimalField(decimal_places=10, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='campaignanalytic',
            name='token_transfer_value_distribution',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='campaignanalytic',
            name='token_transfer_volume',
            field=models.DecimalField(decimal_places=10, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='campaignanalytic',
            name='tot_tokens_transferred',
            field=models.DecimalField(decimal_places=10, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='campaignanalytic',
            name='tot_txn_from_address',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='campaignanalytic',
            name='tot_txn_to_address',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='campaignanalytic',
            name='tot_txns',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='campaignanalytic',
            name='total_contract_calls',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='campaignanalytic',
            name='transaction_value_distribution',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='campaignanalytic',
            name='update_ts',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='communityengagement',
            name='creation_ts',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='communityengagement',
            name='update_ts',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
