# Generated by Django 3.2.14 on 2023-09-18 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytickit', '0006_auto_20230906_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignanalytic',
            name='average_gas_used',
        ),
    ]
