# Generated by Django 3.2.14 on 2023-10-18 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytickit', '0008_auto_20231003_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignanalytic',
            name='average_effective_gas_price',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='campaignanalytic',
            name='change_in_average_gas_price',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='campaignanalytic',
            name='cumulative_avg_gas_price',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='campaignanalytic',
            name='cumulative_gas_used',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='campaignanalytic',
            name='cumulative_transaction_fees',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='campaignanalytic',
            name='cumulative_transactions_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaignanalytic',
            name='daily_percentile_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='campaignanalytic',
            name='daily_standard_deviation',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='campaignanalytic',
            name='gas_price_histogram',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='campaignanalytic',
            name='gas_price_histogram_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='campaignanalytic',
            name='gas_price_max',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='campaignanalytic',
            name='gas_price_min',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='campaignanalytic',
            name='median_effective_gas_price',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='campaignanalytic',
            name='total_daily_fees',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='campaignanalytic',
            name='transactions_by_gas_price_range',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='campaignanalytic',
            name='transactions_relative_prev_day',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='campaignanalytic',
            name='active_users',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campaignanalytic',
            name='ave_gas_used',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='campaignanalytic',
            name='ave_token_transfer_value',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='campaignanalytic',
            name='ave_txn_fee',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='campaignanalytic',
            name='freq_txn',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='campaignanalytic',
            name='function_calls_count',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='campaignanalytic',
            name='most_active_token_addresses',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='campaignanalytic',
            name='referral_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campaignanalytic',
            name='token_flow',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='campaignanalytic',
            name='token_transfer_value',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='campaignanalytic',
            name='token_transfer_value_distribution',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='campaignanalytic',
            name='token_transfer_volume',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='campaignanalytic',
            name='tot_tokens_transferred',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='campaignanalytic',
            name='tot_txn_from_address',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='campaignanalytic',
            name='tot_txn_to_address',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='campaignanalytic',
            name='tot_txns',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campaignanalytic',
            name='total_contract_calls',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campaignanalytic',
            name='transaction_value_distribution',
            field=models.JSONField(default=dict),
        ),
    ]
