# Generated by Django 3.2.14 on 2023-12-14 16:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytickit', '0010_auto_20231018_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(default='Default Campaign', max_length=200, validators=[django.core.validators.MinLengthValidator(1, 'Campaign must have a name!')]),
        ),
    ]
