# Generated by Django 3.2.14 on 2023-12-14 17:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytickit', '0011_alter_team_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorWalletAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_wallet_address', models.CharField(max_length=42)),
                ('visitor_wallet_address_ts', models.DateTimeField()),
                ('creation_ts', models.DateTimeField(auto_now_add=True)),
                ('update_ts', models.DateTimeField(auto_now=True)),
                ('txn_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('token_transfer_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('community_engagement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytickit.communityengagement')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_blockchain_data', related_query_name='user_blockchain_datum', to='analytickit.team')),
            ],
        ),
    ]
