# Generated by Django 3.2.14 on 2023-12-14 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytickit', '0012_visitorwalletaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisitorWalletAddress',
        ),
    ]
