# Generated by Django 3.2.14 on 2024-08-20 23:22

import analytickit.models.crypto.crypto_analytic
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analytickit', '0014_visitorwalletaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoAnalytic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=400, null=True)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
                ('filters', models.JSONField(default=dict)),
                ('filters_hash', models.CharField(blank=True, max_length=400, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('saved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_refresh', models.DateTimeField(blank=True, null=True)),
                ('short_id', models.CharField(blank=True, default=analytickit.models.crypto.crypto_analytic.generate_short_id, max_length=12)),
                ('last_modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_crypto_analytics', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytickit.team')),
            ],
        ),
        migrations.CreateModel(
            name='CryptoDashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=400, null=True)),
                ('description', models.TextField(blank=True)),
                ('pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('filters', models.JSONField(default=dict)),
                ('creation_mode', models.CharField(choices=[('default', 'Default'), ('template', 'Template'), ('duplicate', 'Duplicate')], default='default', max_length=16)),
                ('restriction_level', models.PositiveSmallIntegerField(choices=[(21, 'Everyone in the project can edit'), (37, 'Only those invited to this dashboard can edit')], default=21)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoDashboardTile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layouts', models.JSONField(default=dict)),
                ('color', models.CharField(blank=True, max_length=400, null=True)),
                ('filters_hash', models.CharField(blank=True, max_length=400, null=True)),
                ('last_refresh', models.DateTimeField(blank=True, null=True)),
                ('crypto_analytic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytickit.cryptoanalytic')),
                ('crypto_dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytickit.cryptodashboard')),
            ],
        ),
        migrations.AddField(
            model_name='cryptodashboard',
            name='crypto_insights',
            field=models.ManyToManyField(blank=True, related_name='crypto_dashboards', through='analytickit.CryptoDashboardTile', to='analytickit.CryptoAnalytic'),
        ),
        migrations.AddField(
            model_name='cryptodashboard',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytickit.team'),
        ),
    ]
