# Generated by Django 3.2.14 on 2024-08-30 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytickit', '0015_auto_20240820_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoInsightViewed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_viewed_at', models.DateTimeField()),
                ('crypto_analytic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytickit.cryptoanalytic')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytickit.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='cryptoinsightviewed',
            index=models.Index(fields=['team_id', 'user_id', '-last_viewed_at'], name='analytickit_team_id_b3cd40_idx'),
        ),
        migrations.AddConstraint(
            model_name='cryptoinsightviewed',
            constraint=models.UniqueConstraint(fields=('team', 'user', 'crypto_analytic'), name='unique_crypto_insightviewed'),
        ),
    ]
