# Generated by Django 3.2.14 on 2024-08-30 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytickit', '0016_auto_20240830_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptoanalytic',
            name='dashboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crypto_items', to='analytickit.dashboard'),
        ),
        migrations.AddField(
            model_name='cryptoanalytic',
            name='dive_dashboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytickit.dashboard'),
        ),
    ]
