# Generated by Django 3.2.14 on 2024-09-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytickit', '0017_auto_20240830_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignanalytic',
            name='token_types_count',
            field=models.JSONField(default=dict),
        ),
    ]
