# Generated by Django 3.0.11 on 2021-01-05 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytickit", "0110_sessionrecordingeventbyteamandtimestamp"),
    ]

    operations = [
        migrations.CreateModel(
            name="PluginStorage",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=200)),
                ("value", models.TextField(blank=True, null=True)),
                (
                    "plugin_config",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="analytickit.PluginConfig"),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="pluginstorage",
            constraint=models.UniqueConstraint(
                fields=("plugin_config_id", "key"), name="analytickit_unique_plugin_storage_key"
            ),
        ),
    ]
