# Generated by Django 3.0.11 on 2021-01-26 09:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analytickit", "0116_plugin_latest_tag"),
        ("analytickit", "0116_session_recording_retention_period"),
    ]

    operations = []  # type: ignore
