# Generated by Django 3.0.6 on 2021-04-01 17:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models

import analytickit.models.team


class Migration(migrations.Migration):
    dependencies = [
        ("analytickit", "0141_events_created_at_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="data_attributes",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=analytickit.models.team.get_default_data_attributes
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="timezone",
            field=models.CharField(choices=analytickit.models.team.TIMEZONES, default="UTC", max_length=240),
        ),
    ]
