# Generated by Django 3.1.8 on 2021-05-06 08:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analytickit", "0147_plugin_logs"),
        ("analytickit", "0147_fix_stickiness_dashboard_items"),
    ]

    operations = []  # type: ignore
