# Generated by Django 3.2.5 on 2022-03-16 08:36

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone

import analytickit.models.organization_domain
import analytickit.models.utils


def migrate_domain_whitelist(apps, schema_editor):
    Organization = apps.get_model("analytickit", "Organization")
    OrganizationDomain = apps.get_model("analytickit", "OrganizationDomain")

    for organization in Organization.objects.exclude(domain_whitelist=[]):
        for domain in organization.domain_whitelist:
            OrganizationDomain.objects.create(
                organization=organization, domain=domain, verified_at=timezone.now(), jit_provisioning_enabled=True
            )


class Migration(migrations.Migration):
    dependencies = [
        ("analytickit", "0222_fix_deleted_primary_dashboards"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationDomain",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=analytickit.models.utils.UUIDT, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("domain", models.CharField(max_length=128, unique=True)),
                (
                    "verification_challenge",
                    models.CharField(
                        default=analytickit.models.organization_domain.generate_verification_challenge, max_length=128
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("last_verification_retry", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "jit_provisioning_enabled",
                    models.BooleanField(default=False),
                ),
                # Just-in-time automatic provisioning (user accounts are created on the respective org when logging in with any SSO provider)
                ("sso_enforcement", models.CharField(blank=True, max_length=28)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="domains",
                        to="analytickit.organization"
                    ),
                ),
            ],
            options={"abstract": False, "verbose_name": "domain"},
        ),
        migrations.RunPython(migrate_domain_whitelist, migrations.RunPython.noop),
    ]
