# Generated by Django 3.2.14 on 2022-09-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytickit', '0255_user_prompt_sequence_state'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='action',
            name='analytickit_act_team_id_8c04de_idx',
        ),
        migrations.RemoveIndex(
            model_name='activitylog',
            name='analytickit_act_team_id_13a0a8_idx',
        ),
        migrations.RemoveIndex(
            model_name='cohortpeople',
            name='analytickit_coh_cohort__89c25f_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='analytickit_eve_element_48becd_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='analytickit_eve_timesta_1f6a8c_idx',
        ),
        migrations.RemoveIndex(
            model_name='eventproperty',
            name='analytickit_eve_team_id_22de03_idx',
        ),
        migrations.RemoveIndex(
            model_name='eventproperty',
            name='analytickit_eve_team_id_26dbfb_idx',
        ),
        migrations.RemoveIndex(
            model_name='insightviewed',
            name='analytickit_ins_team_id_339ee0_idx',
        ),
        migrations.RemoveIndex(
            model_name='sessionrecordingevent',
            name='analytickit_ses_team_id_265946_idx',
        ),
        migrations.RemoveIndex(
            model_name='sessionrecordingevent',
            name='analytickit_ses_team_id_46392f_idx',
        ),
        migrations.RemoveIndex(
            model_name='sessionrecordingviewed',
            name='analytickit_ses_team_id_465af1_idx',
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['team_id', '-updated_at'], name='analytickit_team_id_0599e5_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['team_id', 'scope', 'item_id'], name='analytickit_team_id_bacb12_idx'),
        ),
        migrations.AddIndex(
            model_name='cohortpeople',
            index=models.Index(fields=['cohort_id', 'person_id'], name='analytickit_cohort__1d0d4e_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['elements_hash'], name='analytickit_element_4bfb87_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['timestamp', 'team_id', 'event'], name='analytickit_timesta_4e2df5_idx'),
        ),
        migrations.AddIndex(
            model_name='eventproperty',
            index=models.Index(fields=['team', 'event'], name='analytickit_team_id_55947b_idx'),
        ),
        migrations.AddIndex(
            model_name='eventproperty',
            index=models.Index(fields=['team', 'property'], name='analytickit_team_id_d09213_idx'),
        ),
        migrations.AddIndex(
            model_name='insightviewed',
            index=models.Index(fields=['team_id', 'user_id', '-last_viewed_at'], name='analytickit_team_id_6d93ab_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionrecordingevent',
            index=models.Index(fields=['team_id', 'session_id'], name='analytickit_team_id_f733dc_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionrecordingevent',
            index=models.Index(fields=['team_id', 'distinct_id', 'timestamp', 'session_id'], name='analytickit_team_id_d9f6fd_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionrecordingviewed',
            index=models.Index(fields=['team_id', 'user_id', 'session_id'], name='analytickit_team_id_5914aa_idx'),
        ),
    ]
