# Generated by Django 3.2.14 on 2023-09-28 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dpa", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Billing",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("plan_name", models.CharField(default="Free Plan", max_length=255)),
                ("is_metered_billing", models.BooleanField(default=False)),
                ("price", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("event_allowance", models.PositiveIntegerField(default=0)),
                ("billing_period_starts", models.DateField(blank=True, null=True)),
                ("billing_period_ends", models.DateField(blank=True, null=True)),
                ("current_usage", models.PositiveIntegerField(default=0)),
                ("current_bill_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("subscription_url", models.URLField(blank=True, max_length=500, null=True)),
                ("billing_limit", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("billing_limit_exceeded", models.BooleanField(default=False)),
                ("tier_name", models.CharField(blank=True, max_length=255, null=True)),
                ("price_per_event", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("number_of_events_in_tier", models.PositiveIntegerField(blank=True, null=True)),
                ("should_setup_billing", models.BooleanField(default=True)),
                ("is_billing_active", models.BooleanField(default=False)),
                ("should_display_current_bill", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_info",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name": "Billing", "verbose_name_plural": "Billings",},
        ),
    ]
