# Generated by Django 3.2.14 on 2023-10-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpa', '0003_billing_event_allocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='event_allowance',
            field=models.PositiveIntegerField(default=50000),
        ),
    ]
