# Generated by Django 3.2.14 on 2023-12-14 16:34

import datetime
from django.db import migrations, models
import dpa.models.billing


class Migration(migrations.Migration):

    dependencies = [
        ('dpa', '0004_alter_billing_event_allowance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='billing_period_ends',
            field=models.DateField(default=dpa.models.billing.billing_period_ends_default),
        ),
        migrations.AlterField(
            model_name='billing',
            name='billing_period_starts',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
