name: Automerge

env:
  MERGE_METHOD: 'squash'
  MERGE_RETRY_SLEEP: 300000

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  check_suite:
    types:
      - completed
  status: { }

jobs:
  automerge:
    name: Automerge
    runs-on: ubuntu-latest
    env:
      IS_analytickit_BOT_AVAILABLE: ${{ secrets.analytickit_BOT_GITHUB_TOKEN != '' }}
    steps:
      - name: Automerge
        if: env.IS_analytickit_BOT_AVAILABLE == 'true'
        uses: pascalgn/automerge-action@v0.14.2
        env:
          GITHUB_TOKEN: ${{ secrets.analytickit_BOT_GITHUB_TOKEN }}
      - run: echo
