name: Sync analytickit FOSS

on:
    push:
        branches:
            - master
            - main

jobs:
    repo-sync:
        name: Sync analytickit-foss with analytickit
        if: github.repository == 'analytickit/analytickit'
        runs-on: ubuntu-latest
        steps:
            - name: Sync repositories 1 to 1 - master branch
              uses: wei/git-sync@v3
              with:
                  source_repo: 'https://analytickit-bot:${{ secrets.analytickit_BOT_GITHUB_TOKEN }}@github.com/analytickit/analytickit.git'
                  source_branch: 'master'
                  destination_repo: 'https://analytickit-bot:${{ secrets.analytickit_BOT_GITHUB_TOKEN }}@github.com/analytickit/analytickit-foss.git'
                  destination_branch: 'master'
            - name: Sync repositories 1 to 1 – tags
              uses: wei/git-sync@v3
              with:
                  source_repo: 'https://analytickit-bot:${{ secrets.analytickit_BOT_GITHUB_TOKEN }}@github.com/analytickit/analytickit.git'
                  source_branch: 'refs/tags/*'
                  destination_repo: 'https://analytickit-bot:${{ secrets.analytickit_BOT_GITHUB_TOKEN }}@github.com/analytickit/analytickit-foss.git'
                  destination_branch: 'refs/tags/*'
            - name: Checkout analytickit-foss
              uses: actions/checkout@v2
              with:
                  repository: 'analytickit/analytickit-foss'
                  ref: master
                  token: ${{ secrets.analytickit_BOT_GITHUB_TOKEN }}
            - name: Change LICENSE to pure MIT
              run: |
                  sed -i -e '/analytickit Inc\./,/Permission is hereby granted/c\Copyright (c) 2020-2021 analytickit Inc\.\n\nPermission is hereby granted, free of charge, to any person obtaining a copy' LICENSE
                  echo -e "MIT License\n\n$(cat LICENSE)" > LICENSE
            - name: Remove unused GitHub workflows
              run: |
                  cd .github/workflows
                  ls | grep -v foss-release-image-publish.yml | xargs rm

            - name: Commit "Sync and remove all non-FOSS parts"
              uses: EndBug/add-and-commit@v7
              with:
                  message: 'Sync and remove all non-FOSS parts'
                  remove: '["-r dpa/"]'
                  default_author: github_actions
                  github_token: ${{ secrets.analytickit_BOT_GITHUB_TOKEN }}
            - run: echo # Empty step so that GitHub doesn't complain about an empty job on forks
