# Generates the `analytickit/analytickit:foss-latest-release` & `analytickit/analytickit:foss-release-[version]` Docker images
# and pushes to Docker Hub

name: Docker FOSS release image

on:
  push:
    tags:
      - '*.**'

jobs:
  build-push:
    name: Build & push Docker release image
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout default branch
        if: github.repository == 'analytickit/analytickit-foss'
        uses: actions/checkout@v2

      - name: Get tag name
        if: github.repository == 'analytickit/analytickit-foss'
        run: echo "TAG_NAME=$(echo ${GITHUB_REF#refs/tags/} | tr / -)" >> $GITHUB_ENV

      - name: Update git SHA
        if: github.repository == 'analytickit/analytickit-foss'
        run: echo "GIT_SHA = '${GITHUB_SHA}'" > analytickit/gitsha.py

      - name: Set up Depot CLI
        if: github.repository == 'analytickit/analytickit-foss'
        uses: depot/setup-action@v1

      - name: Login to DockerHub
        if: github.repository == 'analytickit/analytickit-foss'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push release
        if: github.repository == 'analytickit/analytickit-foss'
        id: docker-release
        uses: depot/build-push-action@v1
        with:
          context: .
          push: true
          tags: |
            analytickit/analytickit-foss:latest-release
            analytickit/analytickit-foss:release-${{ env.TAG_NAME  }}

      - name: Image digest
        if: github.repository == 'analytickit/analytickit-foss'
        run: |
          echo "Pushed release: ${{ steps.docker-release.outputs.digest }}"
