name: 'Storybook Deployment'

on:
  push:
    branches:
      - master
      - main

jobs:
  storybook-deployment:
    runs-on: ubuntu-latest
    if: github.repository == 'analytickit/analytickit'
    steps:
      - name: Check out analytickit/analytickit repo
        uses: actions/checkout@v2
        with:
          path: analytickit
          fetch-depth: 0

      - name: Install dependencies (yarn)
        run: cd analytickit && yarn

      - name: Build storybook
        run: cd analytickit && yarn build-storybook

      - name: Check out analytickit/storybook-build repo
        uses: actions/checkout@v2
        with:
          path: storybook-build
          repository: analytickit/storybook-build
          token: ${{ secrets.analytickit_BOT_GITHUB_TOKEN }}

      - name: Copy built changes to analytickit/storybook-build repo
        run: |
          # keep the CNAME file, but discard all the rest
          cp storybook-build/docs/CNAME analytickit/storybook-static/
          rm -rf storybook-build/docs
          cp -a analytickit/storybook-static storybook-build/docs

      - name: Commit update
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: storybook-build
          commit_message: 'Storybook build'
          commit_user_name: analytickit Bot
          commit_user_email: hey@analytickit.com
          commit_author: analytickit Bot <hey@analytickit.com>
